name: Build
on:
  pull_request:
  push:
    branches:
      - main
  merge_group:

jobs:
  check:
    name: Check (msrv)
    runs-on: ubuntu-latest
    if: github.repository == 'erasin/wayinfo'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build"

      - name: Run cargo check
        run: cargo check

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    if: github.repository == 'erasin/wayinfo'
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@1.70

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build"

      - name: Cache test tree-sitter grammar
        uses: actions/cache@v4
        with:
          path: runtime/grammars
          key: ${{ runner.os }}-stable-v${{ env.CACHE_VERSION }}-tree-sitter-grammars-${{ hashFiles('languages.toml') }}
          restore-keys: ${{ runner.os }}-stable-v${{ env.CACHE_VERSION }}-tree-sitter-grammars-

      - name: Run cargo test
        run: cargo test 

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

  lints:
    name: Lints
    runs-on: ubuntu-latest
    if: github.repository == 'erasin/wayinfo'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@1.70
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build"

      - name: Run cargo fmt
        run: cargo fmt --all --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Run cargo doc
        run: cargo doc --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: -D warnings

